        <div class="row nomarg">
            <div class="grid_12 footer">
            <div>&copy;Copyright Vetasi Limited 2011</div>
			</div>
        </div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'Google Tracking Code']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script> 



<div id="loadModal">
<div class="text">
<img src="images/bigload.gif" alt="loading" />
<br/>
This may take a while depending on the size of the file.
</div>

</div> 


</div>
    </body>
</html>